export type Page = 'tasks' | 'record' | 'library' | 'models' | 'history' | 'settings' | 'experiments';
export type Target = {pid: number; window_id: number} | {launch_path: string};
export type Profile = {id: string; label: string; repository: string; revision: string; adapter: string;
  engines: string[]; maturity: string; note: string;
  availability: Record<string, {files_present: boolean; missing: string[]; validation: string}>};
export type Engine = {id: string; label: string; context_description: string; context_policy: string};
export type Catalog = {models: Profile[]; inference_backends: Engine[];
  configured_backend?: string; summary_model_present: boolean;
  service: {reachable: boolean; model?: string; backend?: string; error?: string}};
export type Facts = {run_id: string; model: string; profile: string; inference_backend: string;
  execution_backend: string; operation_scope: string; input_mode: string; data_flow: string;
  destination: string; context_description: string; experience_path: string};
export type Run = {job_id: string; task_id: string; instruction: string; status: string; created_at: string;
  updated_at: string; model: string; provider: string; kind: string; error?: string; stop_requested: boolean;
  narrated?: boolean; defer_compilation?: boolean;
  run_facts?: Facts; observed_inference?: {backend: string; context_policy?: string};
  result?: {stop_reason?: string; task_verification_status?: string; performance?: Record<string, number>;
    trace_path?: string; output_directory?: string; narration?: {transcript?: string; segments?: unknown[]; engine?: string}}};
export type Round = {step_index: number; status: string; purpose: string; duration_ms?: number;
  tokens: Record<string, number>; screenshot?: string; executed?: boolean; execution_status?: string;
  verification?: {verdict: string; evidence: string; missing: string}; error?: string; artifact_ref: string};
export type RunEvent = {seq: number; name: string; time: string; trace_id: string;
  attributes: Round & {message?: string; status?: string}};
export type Trace = {id: string; trace_name: string; description: string; representation: string;
  created_at?: string; created_at_source?: 'metadata' | 'file_mtime'};
export type EvidencePicture = {id: string; file: string | null; sha256?: string; width?: number; height?: number; selected?: boolean};
export type TraceModelInput = {content: string; format?: 'raw-evidence-v1' | 'actions-with-images-v2'; images?: EvidencePicture[]; image_selection?: {rule: string}};
export type TraceEvidenceBody = {source_files?: string[]; frames?: EvidencePicture[]; [key: string]: unknown};
export type CompilationConfirmation = {confirmation_required: true; message: string; representation: string;
  existing_versions: (Pick<Trace, 'created_at' | 'created_at_source' | 'trace_name'> & {id?: string; path?: string})[]};
export type TrashItem = {path: string; kind: string; name: string; original_path?: string; deleted_at?: string;
  legacy?: boolean; pending_cleanup?: boolean; file_count?: number; bytes?: number;
  can_restore: boolean; restore_blocked_reason?: string; can_delete: boolean; delete_blocked_reason?: string; can_open?: boolean};
export type Recording = {trace_path: string; local_path: string; task_id?: string; created_at?: string;
  success: boolean; input_events: number; recording_backend: string; narrated?: boolean; narration_chars?: number;
  compilation_supported?: boolean; derivation?: {status: string; action_count?: number}};
export type Revision = {status: string; summary?: string; proposed_revision?: number; blocking_issue_count?: number;
  rules?: unknown[]; guidance_review?: {pending?: unknown[]}; [key: string]: unknown};
export type Candidate = {local_path: string; candidate_id: string; task_id: string; instruction?: string;
  status: string; created_at?: string; source_task?: string; revision?: Revision; task_model_revision?: Revision;
  review_timeline?: {initial_frame?: string; final_frame?: string; rounds?: {before_frame?: string; after_frame?: string; [key: string]: unknown}[]};
  [key: string]: unknown};
export type TaskPack = {path: string; local_path: string; task_id: string; instruction: string; confirmed: boolean;
  actions: string[]; missing_message_capabilities?: string[];
  semantic_experience?: {summary: string; goal: string; revision: number; stage_count: number; state_count: number;
    stages: {id: string; name: string; intent: string; state_before: string; state_after: string; evidence_before: string; evidence_after: string}[];
    states: unknown[]; history: unknown[]; [key: string]: unknown};
  human_guidance?: {summary: string; revision: number; rules: unknown[]; history: unknown[]}; [key: string]: unknown};
export type ModelChoice = {model: string; reasoning_effort: string};
export type AppState = {version: string; active_job: Run | null; trace_representations: Trace[];
  trash?: TrashItem[];
  recordings: Recording[]; candidates: Candidate[]; taskpacks: TaskPack[];
  agent_options: {models: string[]; reasoning_efforts: string[]; defaults: {model: string; reasoning_effort: string};
    compiler_defaults?: ModelChoice; revision_defaults?: ModelChoice; task_model_revision_defaults?: ModelChoice;
    waa_defaults?: {root: string; example_path: string};
    api_defaults: {saved_settings?: {model?: string; base_url?: string; has_saved_key?: boolean;
      response_format?: string; timeout_seconds?: number; context_window_tokens?: number}}}};
export type Config = {provider: 'codex' | 'api' | 'local'; model: string; localModel: string;
  inference: string; executor: 'win32' | 'cua'; scope: 'desktop' | 'selected_windows';
  experience: string; effort: string; apiUrl: string; apiModel: string; apiKey: string;
  apiFormat: string; apiBudget: number; apiTimeout: number;
  targets: {label: string; value: Target}[]; initialTarget: number};
export const active = (run?: Run | null) => !!run && ['queued', 'running', 'stopping', 'awaiting_recording_start', 'awaiting_narration'].includes(run.status);
export const labels: Record<string, string> = {queued: '准备中', running: '运行中', stopping: '正在停止',
  stopped: '已停止', completed: '运行结束', failed: '运行失败', interrupted: '会话中断', partial: '部分完成',
  awaiting_recording_start: '等待录制', awaiting_narration: '等待讲解确认', cancelled: '已取消'};
